export const MICROSERVICE_CREATE_PROCESS_TEMPLATE_STEP_OBJECT_BINDING_PATTERN =
  'v0.1_create_process_template_step_object_binding';
export const MICROSERVICE_FIND_ALL_PROCESS_TEMPLATE_STEP_OBJECT_BINDING_PATTERN =
  'v0.1_list_process_template_step_object_bindings';
export const MICROSERVICE_FIND_ONE_PROCESS_TEMPLATE_STEP_OBJECT_BINDING_PATTERN =
  'v0.1_find_one_process_template_step_object_binding';
export const MICROSERVICE_UPDATE_PROCESS_TEMPLATE_STEP_OBJECT_BINDING_PATTERN =
  'v0.1_update_process_template_step_object_binding';
export const MICROSERVICE_REMOVE_PROCESS_TEMPLATE_STEP_OBJECT_BINDING_PATTERN =
  'v0.1_delete_process_template_step_object_binding';

export const MESSAGE_BROKER_PROCESS_TEMPLATE_STEP_OBJECT_BINDING_SERVICE_CLIENT_TOKEN =
  'process_template_step_object_binding_service_token';
