/** Env keys for dynamic-process rollout (default: disabled). */
export const PROCESS_SUBJECT_MODEL_ENABLED_KEY =
  'PROCESS_SUBJECT_MODEL_ENABLED';

export const PROCESS_CONFIG_OBJECT_STEPS_ENABLED_KEY =
  'PROCESS_CONFIG_OBJECT_STEPS_ENABLED';

export const PROCESS_CALL_PROCESS_ENABLED_KEY = 'PROCESS_CALL_PROCESS_ENABLED';

export const PROCESS_TIER2_INSTANCE_SUBJECT_ENABLED_KEY =
  'PROCESS_TIER2_INSTANCE_SUBJECT_ENABLED';

export const PROCESS_TIER3_WORKFLOW_SUBJECT_ENABLED_KEY =
  'PROCESS_TIER3_WORKFLOW_SUBJECT_ENABLED';

export const PROCESS_TIER1_SCHEDULED_TASK_ENABLED_KEY =
  'PROCESS_TIER1_SCHEDULED_TASK_ENABLED';
