/** Env keys for dynamic-process rollout (default: disabled). */
export const PROCESS_SUBJECT_MODEL_ENABLED_KEY =
  'PROCESS_SUBJECT_MODEL_ENABLED';

export const PROCESS_CONFIG_OBJECT_STEPS_ENABLED_KEY =
  'PROCESS_CONFIG_OBJECT_STEPS_ENABLED';

export const PROCESS_CALL_PROCESS_ENABLED_KEY = 'PROCESS_CALL_PROCESS_ENABLED';

export const PROCESS_TIER2_INSTANCE_SUBJECT_ENABLED_KEY =
  'PROCESS_TIER2_INSTANCE_SUBJECT_ENABLED';

export const PROCESS_TIER3_WORKFLOW_SUBJECT_ENABLED_KEY =
  'PROCESS_TIER3_WORKFLOW_SUBJECT_ENABLED';

export const PROCESS_TIER1_SCHEDULED_TASK_ENABLED_KEY =
  'PROCESS_TIER1_SCHEDULED_TASK_ENABLED';

export const PROCESS_TIER4_SOR_ENTITY_ENABLED_KEY =
  'PROCESS_TIER4_SOR_ENTITY_ENABLED';

export const PROCESS_STEP_ACTIONS_ENABLED_KEY = 'PROCESS_STEP_ACTIONS_ENABLED';

export const PROCESS_EVENT_START_REGISTRY_ENABLED_KEY =
  'PROCESS_EVENT_START_REGISTRY_ENABLED';

export const PROCESS_RUNNER_V2_ENABLED_KEY = 'PROCESS_RUNNER_V2_ENABLED';

export const PROCESS_RUNNER_V3_ENABLED_KEY = 'PROCESS_RUNNER_V3_ENABLED';

export const PROCESS_STEP_ASSIGNEE_SPEC_ENABLED_KEY =
  'PROCESS_STEP_ASSIGNEE_SPEC_ENABLED';

export const PROCESS_STEP_REQUIREMENT_GATE_POLICY_ENABLED_KEY =
  'PROCESS_STEP_REQUIREMENT_GATE_POLICY_ENABLED';
