// TENANT USER INVITATIONS CONTROLLER MESSAGE PATTERNS
export const MICROSERVICE_CREATE_TENANT_USER_INVITATION_PATTERN =
  'v0.1_create_TENANT_USER_INVITATION';
export const MICROSERVICE_FIND_ALL_TENANT_USER_INVITATIONS_PATTERN =
  'v0.1_find_all_TENANT_USER_INVITATIONs';
export const MICROSERVICE_FIND_ONE_TENANT_USER_INVITATION_PATTERN =
  'v0.1_find_one_TENANT_USER_INVITATION';
export const MICROSERVICE_UPDATE_TENANT_USER_INVITATION_PATTERN =
  'v0.1_update_TENANT_USER_INVITATION';
export const MICROSERVICE_REMOVE_TENANT_USER_INVITATION_PATTERN =
  'v0.1_remove_TENANT_USER_INVITATION';
export const MICROSERVICE_FIND_ALL_BY_TENANT_ID_PATTERN =
  'v0.1_find_all_by_tenant_id';
export const MESSAGE_BROKER_TENANT_USER_INVITATION_SERVICE_CLIENT_TOKEN =
  'tenant_user_invitation_service_token';
