// EVENTS CONTROLLER MESSAGE PATTERNS
export const MICROSERVICE_CREATE_EVENT_PATTERN = 'v0.1_create_event';
export const MICROSERVICE_FIND_ALL_EVENT_PATTERN = 'v0.1_find_all_events';
export const MICROSERVICE_FIND_ONE_EVENT_PATTERN = 'v0.1_find_one_event';
export const MICROSERVICE_UPDATE_EVENT_PATTERN = 'v0.1_update_event';
export const MICROSERVICE_REMOVE_EVENT_PATTERN = 'v0.1_remove_event';
// EVENTS CONTROLLER MESSAGE PATTERNS
export const MESSAGE_BROKER_EVENT_SERVICE_CLIENT_TOKEN =
  'event_service_token';
