// PROCESS TEMPLATE STEP TRIGGER CONDITIONS CONTROLLER MESSAGE PATTERNS
export const MICROSERVICE_CREATE_PROCESS_TEMPLATE_STEP_TRIGGER_CONDITION_PATTERN =
  'v0.1_create_process_template_step_trigger_condition';
export const MICROSERVICE_FIND_ALL_PROCESS_TEMPLATE_STEP_TRIGGER_CONDITION_PATTERN =
  'v0.1_find_all_process_template_step_trigger_conditions';
export const MICROSERVICE_FIND_ONE_PROCESS_TEMPLATE_STEP_TRIGGER_CONDITION_PATTERN =
  'v0.1_find_one_process_template_step_trigger_condition';
export const MICROSERVICE_UPDATE_PROCESS_TEMPLATE_STEP_TRIGGER_CONDITION_PATTERN =
  'v0.1_update_process_template_step_trigger_condition';
export const MICROSERVICE_REMOVE_PROCESS_TEMPLATE_STEP_TRIGGER_CONDITION_PATTERN =
  'v0.1_remove_process_template_step_trigger_condition';

export const MESSAGE_BROKER_PROCESS_TEMPLATE_STEP_TRIGGER_CONDITION_SERVICE_CLIENT_TOKEN =
  'process_template_step_trigger_condition_service_token';
