services:
    user-service:
        image: alishoaib3332/unifiedeshop:sixcapi-dev
        container_name: six1-core-api
        ports:
          - "3002:3000"
        volumes:
           - .:/usr/local/app
           - /usr/local/app/node_modules
        command: npm run start:dev

        environment:
          - NODE_ENV=development
          - RABBITMQ_HOST=rabbitmq
        depends_on:
          - mysql
        networks:
          - six1-microservices-network

    mysql:
       image: mysql:latest
       container_name: sixcapi_mysql
       environment:
         MYSQL_ROOT_PASSWORD: sixcapi!1283!
         MYSQL_DATABASE: six1_core_api
         MYSQL_USER: six1ca202412
         MYSQL_PASSWORD: taU4f:?W^HTSBN+Xswn 
       ports:
        - "3307:3306"
       volumes:
        - mysql-data:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d/

       networks:
        - six1-microservices-network  
     
networks:
  six1-microservices-network:
     external: true
    
volumes:
   mysql-data:  

  
              