#user-service/Dockerfile.dev
# Use the official Node.js image as the base image
FROM node:16

# Install passwd package (replacement for shadow-utils) and vim
RUN apt-get update || cat /var/log/apt/term.log && \
    apt-get install -y vim \
    && rm -rf /var/lib/apt/lists/* 

#Create a non-root user for running application (to avoid running as root)    
RUN groupadd -r usdg202501 && useradd -m -r -g usdg202501 usdu202501

#Set environment variables
ENV HOME=/home/usdu202501
ENV NODE_ENV =development

# Set the working directory
WORKDIR /src/local/app

#Copy package.json and package-local.json files to the working directory
COPY package*.json /src/local/app/

#Install the dependencies in development mode
RUN npm install -g @nestjs/cli nodemon && npm install

#Copy the rest of appllication code to the working directory
COPY . /src/local/app/

#Change ownership of /src/local/app directory to a non-root user
RUN chown -R usdu202501:usdg202501 /src/local/app /home/usdu202501

#Switch to non-root user
USER usdu202501

# Build the application
RUN npm run build


# Command to run application
CMD ["npm","run", "start:dev"]
