services:
    user-service:
        image: alishoaib3332/unifiedeshop:us-dev
        container_name: user-service
        ports:
          - "3002:3000"
        volumes:
           - .:/usr/local/app
           - /usr/local/app/node_modules
        command: npm run start:dev

        environment:
          - NODE_ENV=development
          - RABBITMQ_HOST=rabbitmq
        depends_on:
          - mysql
          - redis  
        networks:
          - ueshop-microservices-network

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: us_phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        #PMA_USER: phpmyadmin
        #PMA_PASSWORD: phpmyadmin_password 
        PMA_ARBITRARY: 1
      ports:
        - "8081:80"
      depends_on:
        - mysql
      networks:
        - ueshop-microservices-network      

    mysql:
       image: mysql:latest
       container_name: us_mysql
       environment:
         MYSQL_ROOT_PASSWORD: ueshopusrp
         MYSQL_DATABASE: ueshop_users
         MYSQL_USER: ueshopudu
         MYSQL_PASSWORD: ueshopudp 
       ports:
        - "3307:3306"
       volumes:
        - mysql-data:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d/

       networks:
        - ueshop-microservices-network  

    redis:
      image: redis:latest
      container_name: us_redis
      ports:
        - "6380:6379"
      networks:
        - ueshop-microservices-network 
     
networks:
  ueshop-microservices-network:
     external: true
    
volumes:
   mysql-data:  

  
              