services:
    six1-core-api:
        build:
         platform: linux/amd64
         context: ..
         dockerfile: docker-files/Dockerfile   
        image: alishoaib3332/six1-core-api:prod
        container_name: six1-core-api-prod
        ports:
          - "3002:3000"
        environment:
          - NODE_ENV=${NODE_ENV}
          - SIX1_CORE_API_DB_HOST=mysql
          - SIX1_CORE_API_DB_PORT=3306
          - SIX1_CORE_API_DB_USERNAME=${SIX1_CORE_API_DB_USERNAME}
          - SIX1_CORE_API_DB_PASSWORD=${SIX1_CORE_API_DB_PASSWORD}
          - SIX1_CORE_API_DB_DATABASE=${SIX1_CORE_API_DB_DATABASE}
          - RABBITMQ_HOST=${RABBITMQ_HOST}
          - JWT_SECRET_KEY=${JWT_SECRET_KEY}
          - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
          - MESSAGE_BROKER_QUEUE_NAME=${SIX1_CORE_API_MESSAGE_BROKER_QUEUE_NAME}
          - MESSAGE_BROKER_URL=${MESSAGE_BROKER_URL}
        depends_on:
          - mysql
        networks:
          - six1-microservices-network

    mysql:
       image: mysql:latest
       container_name: six1-core-api-prod-mysql
       environment:
         MYSQL_ROOT_PASSWORD: ${SIX1_CORE_API_MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${SIX1_CORE_API_DB_DATABASE} 
         MYSQL_USER: ${SIX1_CORE_API_DB_USERNAME}
         MYSQL_PASSWORD: ${SIX1_CORE_API_DB_PASSWORD} 
       ports:
        - "3307:3306"
       volumes:
        - mysql-data:/var/lib/mysql
        - ../db:/docker-entrypoint-initdb.d/
       networks:
        - six1-microservices-network  
     
networks:
  ueshop-microservices-network:
     external: true
    
volumes:
   mysql-data:  

  
              