services:
    six1-core-api:
        build:
         platform: linux/amd64
         context: ../
         dockerfile: docker-files/Dockerfile.dev   
        image: alishoaib3332/six1-core-api:dev
        container_name: six1-core-api-dev
        ports:
          - "50004:3000"
        volumes:
           - ..:/src/local/app/
           - /src/local/app/node_modules
        command: npm run start:dev
        environment:
          - NODE_ENV=${NODE_ENV}
        depends_on:
          - mysql
          - redis-six1-core-api-dev
        networks:
          - six1-microservices-network

    redis-six1-core-api-dev:
        image: redis:latest
        container_name: redis-core-api-dev
        restart: unless-stopped
        command:
          ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        ports:
          - "6382:6379"
        volumes:
          - redis_six1_core_api_dev_data:/data
        networks:
          - six1-microservices-network         

    phpmyadmin:
           image: phpmyadmin/phpmyadmin:latest
           container_name: six1-phpmyadmin
           environment:
                PMA_HOST: mysql
                PMA_PORT: 3306
                PMA_ARBITRARY: 1
           ports:
              - "8088:80"
           depends_on:
              - mysql
           networks:
             - six1-microservices-network          

    mysql:
       image: mysql:8.0 
       container_name: six1-core-api-dev-mysql
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: ${SIX1_CORE_API_MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${SIX1_CORE_API_DB_DATABASE} 
         MYSQL_USER: ${SIX1_CORE_API_DB_USERNAME}
         MYSQL_PASSWORD: ${SIX1_CORE_API_DB_PASSWORD} 
       ports:
        - "3307:3306"
       volumes:
        - mysql-data:/var/lib/mysql
        - ../db:/docker-entrypoint-initdb.d/

       networks:
        - six1-microservices-network  
     
networks:
  six1-microservices-network:
     external: true
    
volumes:
   mysql-data:  
   redis_six1_core_api_dev_data:

  
              