# Stage 1: Build the application
FROM node:16 AS builder


# Create a non-root user for running the application
RUN groupadd -r six1capiuatg202507 && useradd -m -r -g six1capiuatg202507 six1capiuatu202507

# Set environment variable correctly
ENV NODE_ENV=uat
ENV HOME=/home/six1capiuatu202507

# Set the working directory
WORKDIR /src/local/app

# Copy package.json and package-lock.json files to the working directory
COPY ../package*.json /src/local/app

# Install all dependencies (including dev dependencies)
RUN npm install -g @nestjs/cli && npm install && npm install --save-dev @types/passport-jwt

# Copy the rest of the application files
COPY ../ /src/local/app/

# Build the application
RUN npm run build

# Stage 2: Prepare the final production image
FROM node:16

# Set environment variable for production
ENV NODE_ENV=uat
ENV HOME=/home/six1capiuatu202507

# Create a non-root user for running the application
RUN groupadd -r six1capiuatg202507 && useradd -m -r -g six1capiuatg202507 six1capiuatu202507

# Set the working directory
WORKDIR /src/local/app

# Copy only production dependencies
COPY ../package*.json /src/local/app/
RUN npm install --only=production

# Copy built application from the builder stage
COPY --from=builder /src/local/app/dist ./dist

# Change ownership of the application directory to the non-root user
RUN chown -R six1capiuatu202507:six1capiuatg202507 /src/local/app /home/six1capiuatu202507

# Switch to the non-root user
USER six1capiuatu202507

# Start the application (run DB migrations first)
CMD ["sh", "-c", "npm run migration:run:dist && npm run start:prod"]
