export const NO_RECORD_FOUND_MESSAGE = 'No record found for {entity_name}.';

export const NO_RECORD_FOUND_FOR_PASSED_FILTERS_MESSAGE =
  'No {entity_name} record found.Please change filter params.';

//Message broker constats
export const MESSAGE_BROKER_USERNAME_KEY = 'MESSAGE_BROKER_USERNAME';
export const MESSAGE_BROKER_PASSWORD_KEY = 'MESSAGE_BROKER_PASSWORD';
export const MESSAGE_BROKER_HOST_KEY = 'MESSAGE_BROKER_HOST';
export const MESSAGE_BROKER_PORT_KEY = 'MESSAGE_BROKER_PORT';
export const MESSAGE_BROKER_URL_KEY = 'MESSAGE_BROKER_URL';
export const SERVICE_MESSAGE_BROKER_QUEUE_NAME_KEY =
  'SERVICE_MESSAGE_BROKER_QUEUE_NAME';

//Error messages
export const ENVIRONMENT_VARIABLE_NOT_FOUND_ERROR_MESSAGE =
  'No value found from environment file for you passed key:{key}.';
export const NOT_DEFINED_ERROR_MESSAGE = 'The passed value is not defined';

export const PROCESS_TEMPLATE_NOT_PUBLISHED_MESSAGE =
  'Process template must be PUBLISHED before it can be used to start a process.';

export const DEFAULT_ENVIRONMENT_FILE_NAME = '.env.production';
export const DATABASE_SERVICE_TYPE = 'mysql';

//MYSQL database constats
export const MYSQL_DATABASE_HOST_NAME_KEY = 'SIX1_CORE_API_DB_HOST';
export const MYSQL_DATABASE_PORT_KEY = 'SIX1_CORE_API_DB_PORT';
export const MYSQL_DATABASE_USER_NAME_KEY = 'SIX1_CORE_API_DB_USERNAME';
export const MYSQL_DATABASE_PASSWORD_KEY = 'SIX1_CORE_API_DB_PASSWORD';
export const MYSQL_DATABASE_NAME_KEY = 'SIX1_CORE_API_DB_DATABASE';

//Storage constats
export const STORAGE_DRIVER = 'SIX1_STORAGE_DRIVER';

// R2 (Cloudflare)
export const R2_ACCOUNT_ID = 'SIX1_R2_ACCOUNT_ID';
export const R2_ACCESS_KEY_ID = 'SIX1_R2_ACCESS_KEY_ID';
export const R2_SECRET_ACCESS_KEY = 'SIX1_R2_SECRET_ACCESS_KEY';
export const R2_BUCKET = 'SIX1_R2_BUCKET';

//AWS S3 (if STORAGE_DRIVER=s3)
export const S3_REGION = 'SIX1_S3_REGION';
export const S3_ACCESS_KEY_ID = 'SIX1_S3_ACCESS_KEY_ID';
export const S3_SECRET_ACCESS_KEY = 'SIX1_S3_SECRET_ACCESS_KEY';
export const S3_BUCKET = 'SIX1_S3_BUCKET';

//Local (if STORAGE_DRIVER=local)
export const LOCAL_STORAGE_DIR = 'SIX1_LOCAL_STORAGE_DIR';
export const LOCAL_PUBLIC_BASE_URL = 'SIX1_LOCAL_PUBLIC_BASE_URL';

// Notification public base URL for template links
export const NOTIFICATION_PUBLIC_BASE_URL_KEY = 'NOTIFICATION_PUBLIC_BASE_URL';

// Notification SMTP
export const NOTIFICATION_SMTP_HOST_KEY = 'NOTIFICATION_SMTP_HOST';
export const NOTIFICATION_SMTP_PORT_KEY = 'NOTIFICATION_SMTP_PORT';
export const NOTIFICATION_SMTP_USER_KEY = 'NOTIFICATION_SMTP_USER';
export const NOTIFICATION_SMTP_PASSWORD_KEY = 'NOTIFICATION_SMTP_PASSWORD';
export const NOTIFICATION_SMTP_FROM_NAME_KEY = 'NOTIFICATION_SMTP_FROM_NAME';
export const NOTIFICATION_SMTP_FROM_EMAIL_KEY = 'NOTIFICATION_SMTP_FROM_EMAIL';
export const NOTIFICATION_SMTP_SECURE_KEY = 'NOTIFICATION_SMTP_SECURE';

// Notification SMS (Twilio)
export const NOTIFICATION_TWILIO_ACCOUNT_SID_KEY =
  'NOTIFICATION_TWILIO_ACCOUNT_SID';
export const NOTIFICATION_TWILIO_AUTH_TOKEN_KEY =
  'NOTIFICATION_TWILIO_AUTH_TOKEN';
export const NOTIFICATION_TWILIO_FROM_NUMBER_KEY =
  'NOTIFICATION_TWILIO_FROM_NUMBER';

// Notification Push (Firebase)
export const NOTIFICATION_FIREBASE_SERVICE_ACCOUNT_JSON_KEY =
  'NOTIFICATION_FIREBASE_SERVICE_ACCOUNT_JSON';

// User meta keys
export const USER_META_PHONE_NUMBER_KEY = 'USER_META_PHONE_NUMBER_KEY';
export const USER_META_PUSH_TOKEN_KEY = 'USER_META_PUSH_TOKEN_KEY';
